name: 機能リクエスト
description: 新機能の提案・追加要望
title: "feat: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        新機能の提案ありがとうございます。
        以下のテンプレートに沿って記載してください。

  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: 実装したい機能の概要を簡潔に記載してください
      placeholder: |
        例: 馬番号バッジの色をJRA公式の枠色に合わせたい
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 背景・動機
      description: なぜこの機能が必要なのか、どのような課題を解決するのかを記載してください
      placeholder: |
        例: 現在の色がJRA公式と異なり、ユーザーの直感に反するため修正したい
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: 現状
      description: |
        現在の状態（関連コード、スクリーンショットなど）を記載してください
        ファイルパスやコード例があると実装がスムーズになります
      placeholder: |
        **ファイル**: `frontend/src/types/index.ts`

        ```typescript
        // 現在のコード
        ```

        **問題点**:
        - ...
    validations:
      required: false

  - type: textarea
    id: proposed-solution
    attributes:
      label: 提案する解決策
      description: どのように実装すべきか、技術的な考慮点があれば記載してください
      placeholder: |
        ## 実装方針

        ### バックエンド
        - DBスキーマの変更
        - API修正

        ### フロントエンド
        - コンポーネント修正

        ## 技術的考慮点
        - パフォーマンス
        - 互換性
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: タスク
      description: 実装に必要なタスクをチェックリストで記載してください
      placeholder: |
        ### バックエンド
        - [ ] DBスキーマ修正
        - [ ] API修正
        - [ ] テスト追加

        ### フロントエンド
        - [ ] コンポーネント修正
        - [ ] テスト追加
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 受け入れ条件
      description: この機能が完成したとみなす条件を記載してください
      placeholder: |
        - [ ] 〇〇が表示される
        - [ ] △△の場合に□□が動作する
        - [ ] テストが通る
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: 参考資料
      description: 参考になるドキュメント、デザイン、スクリーンショットなどがあれば記載してください
      placeholder: |
        - [JRA公式サイト](https://www.jra.go.jp/)
        - デザインモック: ...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 補足情報
      description: その他補足があれば記載してください
    validations:
      required: false
